name: My CI Workflow  # Optional but good to include a name for the workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the environment to run on

    steps:
      - name: 23f2000232@ds.study.iitm.ac.in
        run: echo "Hello, world!"  # The command to run
