name: Daily Commit

on:
  schedule:
    - cron: "25 30 * * *"  # Runs daily at 22:25 UTC (10:25 PM UTC)

  workflow_dispatch:  # Allows manual trigger

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add a commit step 23f2000232@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date)" > daily_update.txt
          
